name: reem_verse_rebuild
description: A clean rebuilt version of ReemVerse app ðŸ§ 
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & Utility
  intl: ^0.20.2
  provider: ^6.1.1
  url_launcher: ^6.2.5
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.9.1
  flutter_riverpod: ^2.5.1 # Ø¥Ù† ÙƒÙ†Øª ØªØ³ØªØ®Ø¯Ù…Ù‡
  image_picker: ^1.1.0 # Ù„Ø±ÙØ¹ Ø§Ù„ØµÙˆØ±
  path_provider: ^2.1.2
  http: ^1.2.2


  # âœ… Social login
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1

  # âœ… Media & Location
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.1 # âœ… Ù…ØªÙˆØ§ÙÙ‚

  # âœ… UI & Interactions
  cupertino_icons: ^1.0.2
  swipe_cards: ^2.0.0+1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/fonts/
    - assets/icons/
